#  Copyright (c) 2021 VMware, Inc. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Build

on:
  push:
    branches: ["main", "master"]

  pull_request:
    branches: ["main", "master"]

  # also run every night
  schedule:
    - cron: "0 1 * * *"

jobs:
  artifacts:
    name: Build Snapshot Release (no upload)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --snapshot # snapshot will disable push/release
      - name: Verify git clean
        shell: bash
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "${{ github.repository }} up to date."
          else
            echo "${{ github.repository }} is dirty."
            echo "::error:: $(git status)"
            exit 1
          fi
      # make artifacts available for inspection
      # https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts
      - name: Archive run artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          # upload only some artifacts for introspection to keep storage size small (delete after 1d)
          path: |
            dist/govc_*x86_64.tar.gz
            dist/vcsim_*x86_64.tar.gz
            dist/checksums.txt
          retention-days: 1
